require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

