name: "Deploy"
on:
  push:
    branches: [ "main" ]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/sergio-fry/bills.git"
          source_branch: "main"
          destination_repo: "destination_org/repository"
          destination_branch: "main"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
